name: Build iOS IPA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '<flutter_version>' # Specify Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: pod install --project-directory=ios

    - name: Prepare Code Signing
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/YourProfile.mobileprovision
        echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
        security import certificate.p12 -P "$CERTIFICATE_PASSWORD" -A

    - name: Build IPA
      run: flutter build ios --release --no-codesign

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
        -archivePath build/ios/archive.xcarchive \
        -exportPath build/ios/ipa \
        -exportOptionsPlist ios/exportOptions.plist

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: build/ios/ipa
